services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # Install the project once after building
    # Note: Seems to be ignored by devcontainer, so use postCreateCommand instead
    #post_start:
    #  - command: bun install
    # Mount the project folder
    volumes:
      - ..:/workspace:cached,Z
    # Load environment variables
    env_file:
      - ./secrets.env
    # Use bridge network mode
    network_mode: bridge
    ports:
      - "4321:4321"
    # Keep the container running
    command: sleep infinity
